site_name: momentGW
docs_dir: docs
watch:
- momentGW
theme:
  name: material

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_files.py
- section-index
- include-markdown
- mkdocstrings:
    default_handler: python
    handlers:
        python:
            rendering:
                show_source: false
            options:
                docstring_style: numpy
                members_order: source
                line_length: 72
                merge_init_into_class: true
                show_if_no_docstring: false
                show_root_members_full_path: true
                show_object_full_path: true

nav:
- Home: "index.md"
- Code reference:
  - RHF:
    - base: references/base/index.html
    - gw: references/gw/index.html
    - evgw: references/evgw/index.html
    - fsgw: references/fsgw/index.html
    - qsgw: references/qsgw/index.html
    - scgw: references/scgw/index.html
    - tda: references/tda/index.html
    - rpa: references/rpa/index.html
    - bse: references/bse/index.html
    - thc: references/thc/index.html
    - ints: reference/ints/index.html
    - fock: reference/fock/index.html
    - energy: reference/energy/index.html
    - logging: reference/logging/index.html
    - util: reference/util/index.html
  - UHF:
    - base: references/uhf/base/index.html
    - gw: references/uhf/gw/index.html
    - evgw: references/uhf/evgw/index.html
    - fsgw: references/uhf/fsgw/index.html
    - qsgw: references/uhf/qsgw/index.html
    - scgw: references/uhf/scgw/index.html
    - tda: references/uhf/tda/index.html
    - rpa: references/uhf/rpa/index.html
    - ints: reference/uhf/ints/index.html
    - fock: reference/uhf/fock/index.html
  - KRHF:
    - base: references/pbc/base/index.html
    - gw: references/pbc/gw/index.html
    - evgw: references/pbc/evgw/index.html
    - fsgw: references/pbc/fsgw/index.html
    - qsgw: references/pbc/qsgw/index.html
    - scgw: references/pbc/scgw/index.html
    - tda: references/pbc/tda/index.html
    - rpa: references/pbc/rpa/index.html
    - kpts: references/pbc/kpts/index.html
    - ints: reference/pbc/ints/index.html
    - fock: reference/pbc/fock/index.html
  - KUHF:
    - base: references/pbc/uhf/base/index.html
    - gw: references/pbc/uhf/gw/index.html
    - evgw: references/pbc/uhf/evgw/index.html
    - fsgw: references/pbc/uhf/fsgw/index.html
    - qsgw: references/pbc/uhf/qsgw/index.html
    - scgw: references/pbc/uhf/scgw/index.html
    - tda: references/pbc/uhf/tda/index.html
    - ints: reference/pbc/uhf/ints/index.html
    - fock: reference/pbc/uhf/fock/index.html
