name: CI

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    name: python "3.11" on ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install momentGW
        run: |
          python -m pip install wheel
          python -m pip install .[dev]
      - name: Linting
        run: |
          python -m black . --diff --check --verbose
          python -m isort . --diff --check-only --verbose
          python -m flake8 momentGW/ --verbose
      #- name: Run unit tests
      #  run: |
      #    python -m pip install pytest pytest-cov
      #    pytest --cov momentGW/
      - name: Deploy documentation
        run: mkdocs gh-deploy --force -f docs/mkdocs.yaml
        #if: github.ref == 'refs/heads/master'
