name: CI

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python: ["3.11", "3.12", "3.13"]
      fail-fast: false

    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install momentGW
        run: |
          python -m pip install wheel
          python -m pip install .[dev]
      - name: Linting
        run: |
          ruff check
          ruff format --check
      - name: Run unit tests
        run: |
          python -m pip install pytest pytest-cov
          pytest --cov momentGW/
